development:
  url: <%= "postgresql://development:development@localhost:5432/gitlab_notifier" %>

test:
  url: <%= "postgresql://development:development@localhost:5432/gitlab_notifier_test" %>

production:
  url: <%= ENV["DATABASE_URL"] %>
