development:
  url: <%= ENV["DATABASE_URL"] %>

test:
  url: <%= ENV["DATABASE_URL"] %>

production:
  url: <%= ENV["DATABASE_URL"] %>

cable:
  url: <%= ENV["DATABASE_URL"] %>

cache:
  url: <%= ENV["DATABASE_URL"] %>
